# Generated by Django 4.2.24 on 2025-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
