# Generated by Django 4.2.24 on 2025-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_song_artist_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify',
            field=models.TextField(blank=True, null=True),
        ),
    ]
