# Generated by Django 5.2.6 on 2025-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_song_spotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='spotify',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
