# Generated by Django 4.2.24 on 2025-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_graduate_spotify_delete_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='married',
            field=models.TextField(default=False),
        ),
    ]
