# Generated by Django 5.2.6 on 2025-11-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_graduate_married'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduate',
            old_name='for_linda',
            new_name='memoriam',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='for_zaza',
        ),
    ]
