# Generated by Django 5.2.6 on 2025-11-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_for_linda_graduate_memoriam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
